apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
    name: roomman-service
  spec:
    selector:
      app: roomman
    ports:
      - protocol: TCP
        port: 8812
        targetPort: 8812
- apiVersion: v1
  kind: Service
  metadata:
    name: booking-service
  spec:
    selector:
      app: booking
    ports:
      - protocol: TCP
        port: 8813
        targetPort: 8813
- apiVersion: v1
  kind: Service
  metadata:
    name: user-service
  spec:
    selector:
      app: user
    ports:
      - protocol: TCP
        port: 8815
        targetPort: 8815
- apiVersion: v1
  kind: Service
  metadata:
    name: contentlib-service
  spec:
    selector:
      app: contentlib
    ports:
      - protocol: TCP
        port: 8821
        targetPort: 8821
- apiVersion: v1
  kind: Service
  metadata:
    name: payment-service
  spec:
    selector:
      app: payment
    ports:
      - protocol: TCP
        port: 8817
        targetPort: 8817
- apiVersion: v1
  kind: Service
  metadata:
    name: auth-service
  spec:
    selector:
      app: auth
    ports:
      - protocol: TCP
        port: 8491
        targetPort: 8491