  version: "3.8"

  services:
    gateway:
      image: studionestapi.azurecr.io/gateway-service:latest
      container_name: api-service
      build:
        context: ./server
        dockerfile: ./src/main/gateway/Dockerfile
      ports:
        - "8080:8080"
      networks:
        - studionest

    auth:
      image: studionestapi.azurecr.io/auth-service:latest
      container_name: auth-service
      build: 
        context: ./server
        dockerfile: ./src/main/auth/Dockerfile
      ports:
        - "8491:8491"
      env_file:
        - ./server/src/main/auth/app/.env
      networks:
        - studionest
    roomman:
      image: studionestapi.azurecr.io/roomman-service:latest
      container_name: roomman-service
      build: 
        context: ./server
        dockerfile: ./src/main/roomman/Dockerfile
      ports:
        - "8812:8812"
      env_file:
        - ./server/src/main/roomman/app/.env
      networks:
        - studionest

    booking:
      image: studionestapi.azurecr.io/booking-service:latest
      container_name: booking-service
      build: 
        context: ./server
        dockerfile: ./src/main/booking/Dockerfile
      ports:
        - "8813:8813"
      env_file:
        - ./server/src/main/booking/app/.env
      networks:
        - studionest
    user:
      image: studionestapi.azurecr.io/user-service:latest
      container_name: user-service
      build: 
        context: ./server
        dockerfile: ./src/main/user/Dockerfile
      env_file:
        - ./server/src/main/user/app/.env
      ports:
        - "8815:8815"
      networks:
        - studionest

    payment:
      image: studionestapi.azurecr.io/payment-service:latest
      container_name: payment-service
      build: 
        context: ./server
        dockerfile: ./src/main/payment/Dockerfile
      env_file:
        - ./server/src/main/payment/app/.env
      ports:
        - "8822:8822"
      networks:
        - studionest

    contentlib:
      image: studionestapi.azurecr.io/contentlib-service:latest
      container_name: contentlib-service
      build: 
        context: ./server
        dockerfile: ./src/main/contentlib/Dockerfile
      ports:
        - "8821:8821"
      env_file:
        - ./server/src/main/contentlib/app/.env
      networks:
        - studionest
    aihelper:
      image: studionestapi.azurecr.io/aihelper-service:latest
      container_name: aihelper-service
      build: 
        context: ./server
        dockerfile: ./src/main/aihelper/Dockerfile
      ports:
        - "8840:8840"
      env_file:
        - ./server/src/main/aihelper/app/.env
      networks:
        - studionest
    client:
      image: studionestapi.azurecr.io/client-service:latest
      container_name: client-service
      restart: always
      build:
        context: ./client
        dockerfile: ./Dockerfile
      volumes:
        - ./client:/app
        - /app/node_modules
        - /app/.next
      ports: 
        - "3000:3000"
      networks:
        - studionest
  networks:
    studionest: