  version: "3.8"

  services:
    gateway:
      image: 628421111437.dkr.ecr.eu-north-1.amazonaws.com/studionest:gateway
      container_name: api-service
      build: ./server/src/main/gateway
      ports:
        - "8080:8080"
      networks:
        - studionest

    auth:
      image: 628421111437.dkr.ecr.eu-north-1.amazonaws.com/studionest:auth
      container_name: auth-service
      build: 
        context: ./server/src/main
        dockerfile: ./auth/Dockerfile
      ports:
        - "8491:8491"
      env_file:
        - ./server/src/main/auth/app/.env
      networks:
        - studionest
    roomman:
      image: 628421111437.dkr.ecr.eu-north-1.amazonaws.com/studionest:roomman
      container_name: roomman-service
      build: 
        context: ./server/src/main
        dockerfile: ./roomman/Dockerfile
      ports:
        - "8812:8812"
      env_file:
        - ./server/src/main/roomman/app/.env
      networks:
        - studionest

    booking:
      image: 628421111437.dkr.ecr.eu-north-1.amazonaws.com/studionest:booking
      container_name: booking-service
      build: 
        context: ./server/src/main
        dockerfile: ./booking/Dockerfile
      ports:
        - "8813:8813"
      env_file:
        - ./server/src/main/booking/app/.env
      networks:
        - studionest
    user:
      image: 628421111437.dkr.ecr.eu-north-1.amazonaws.com/studionest:user
      container_name: user-service
      build: 
        context: ./server/src/main
        dockerfile: ./user/Dockerfile
      env_file:
        - ./server/src/main/user/app/.env
      ports:
        - "8815:8815"
      networks:
        - studionest

    payment:
      image: 628421111437.dkr.ecr.eu-north-1.amazonaws.com/studionest:payment
      container_name: payment-service
      build: 
        context: ./server/src/main
        dockerfile: ./payment/Dockerfile
      env_file:
        - ./server/src/main/payment/app/.env
      ports:
        - "8822:8822"
      networks:
        - studionest

    contentlib:
      image: 628421111437.dkr.ecr.eu-north-1.amazonaws.com/studionest:contentlib
      container_name: contentlib-service
      build: 
        context: ./server/src/main
        dockerfile: ./contentlib/Dockerfile
      ports:
        - "8821:8821"
      env_file:
        - ./server/src/main/contentlib/app/.env
      networks:
        - studionest
    # client:
    #   image: 628421111437.dkr.ecr.eu-north-1.amazonaws.com/studionest:client
    #   container_name: client-service
    #   build: "./web"
    #   ports: 
    #     - "3000:3000"
    frontend:
      build:
        context: ./client
        dockerfile: Dockerfile
      ports:
        - "3000:3000"
      volumes:
        - ./client:/app
        - /app/node_modules
      networks:
        - studionest
  networks:
    studionest: