apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        image: 628421111437.dkr.ecr.eu-north-1.amazonaws.com/studionest:gateway
        ports:
        - containerPort: 8080
