apiVersion: v1
kind: List
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: api
  spec:
    selector:
      matchLabels:
        app: api
    template:
      metadata:
        labels:
          app: api
      spec:
        containers:
        - name: api
          image: "628421111437.dkr.ecr.eu-north-1.amazonaws.com/api:latest"
          imagePullPolicy: Always
          ports:
          - containerPort: 8080
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 50m
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: roomman
  spec:
    selector:
      matchLabels:
        app: roomman
    template:
      metadata:
        labels:
          app: roomman
      spec:
        containers:
        - name: roomman
          image: "628421111437.dkr.ecr.eu-north-1.amazonaws.com/roomman:latest"
          imagePullPolicy: Always
          ports:
          - containerPort: 8812
          env:
          - name: MONGODB
            valueFrom:
              secretKeyRef:
                name: roomman-secret
                key: ROOMMAN_MONGODB_CONNECTION_STRING
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 50m
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: booking
  spec:
    selector:
      matchLabels:
        app: booking
    template:
      metadata:
        labels:
          app: booking
      spec:
        containers:
        - name: booking
          image: "628421111437.dkr.ecr.eu-north-1.amazonaws.com/booking:latest"
          imagePullPolicy: Always
          ports:
          - containerPort: 8813
          env:
          - name: MONGODB
            valueFrom:
              secretKeyRef:
                name: booking-secret
                key: BOOKING_MONGODB_CONNECTION_STRING
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 50m
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: user
  spec:
    selector:
      matchLabels:
        app: user
    template:
      metadata:
        labels:
          app: user
      spec:
        containers:
        - name: user
          image: "628421111437.dkr.ecr.eu-north-1.amazonaws.com/user:latest"
          imagePullPolicy: Always
          ports:
          - containerPort: 8815
          env:
          - name: MONGODB
            valueFrom:
              secretKeyRef:
                name: user-secret
                key: USER_MONGODB_CONNECTION_STRING
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 50m
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: contentlib
  spec:
    selector:
      matchLabels:
        app: contentlib
    template:
      metadata:
        labels:
          app: contentlib
      spec:
        containers:
        - name: contentlib
          image: "628421111437.dkr.ecr.eu-north-1.amazonaws.com/contentlib:latest"
          imagePullPolicy: Always
          ports:
          - containerPort: 8821
          env:
          - name: MONGODB
            valueFrom:
              secretKeyRef:
                name: contentlib-secret
                key: CONTENTLIB_MONGODB_CONNECTION_STRING
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 50m
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: payment
  spec:
    selector:
      matchLabels:
        app: payment
    template:
      metadata:
        labels:
          app: payment
      spec:
        containers:
        - name: payment
          image: "628421111437.dkr.ecr.eu-north-1.amazonaws.com/payment:latest"
          imagePullPolicy: Always
          ports:
          - containerPort: 8817
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 50m
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: auth
  spec:
    selector:
      matchLabels:
        app: auth
    template:
      metadata:
        labels:
          app: auth
      spec:
        containers:
        - name: auth
          image: "628421111437.dkr.ecr.eu-north-1.amazonaws.com/auth:latest"
          imagePullPolicy: Always
          ports:
          - containerPort: 8491
          env:
          - name: MONGODB
            valueFrom:
              secretKeyRef:
                name: auth-secret
                key: AUTH_MONGODB_CONNECTION_STRING
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 50m
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: client
  spec:
    selector:
      matchLabels:
        app: client
    template:
      metadata:
        labels:
          app: client
      spec:
        containers:
        - name: client
          image: "628421111437.dkr.ecr.eu-north-1.amazonaws.com/client:latest"
          imagePullPolicy: Always
          ports:
          - containerPort: 3000
          env:
          - name: HOST
            valueFrom:
              secretKeyRef:
                name: client-secret
                key: CLIENT_HOST
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 50m
