apiVersion: v1
kind: List
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: api
  spec:
    selector:
      matchLabels:
        app: api
    template:
      metadata:
        labels:
          app: api
      spec:
        imagePullSecrets:
        - name: acr-auth
        containers:
        - name: api
          image: "studionestapi.azurecr.io/gateway-service:latest"
          imagePullPolicy: Always
          ports:
          - containerPort: 8080
          resources:
            requests:
              cpu: 50m  # 50 (0.05 CPU cores)
              memory: 256Mi  
            limits:
              cpu: 300m  #  (0.5 CPU cores)
              memory: 512Gi 
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: roomman
  spec:
    selector:
      matchLabels:
        app: roomman
    template:
      metadata:
        labels:
          app: roomman
      spec:
        imagePullSecrets:
        - name: acr-auth
        containers:
        - name: roomman
          image: "studionestapi.azurecr.io/roomman-service:latest"
          imagePullPolicy: Always
          ports:
          - containerPort: 8812
          env:
          - name: MONGODB
            valueFrom:
              secretKeyRef:
                name: roomman-secret
                key: MONGODB_CONNECTION_STRING
          - name: AZURE_STORAGE_CONTAINER
            valueFrom:
              secretKeyRef:
                name: roomman-secret
                key: AZURE_STORAGE_CONTAINER
          - name: AZURE_STORAGE_CONNECTION
            valueFrom:
              secretKeyRef:
                name: roomman-secret
                key: AZURE_STORAGE_CONNECTION
          resources:
            requests:
              cpu: 50m  # 50 (0.05 CPU cores)
              memory: 256Mi  
            limits:
              cpu: 300m  #  (0.5 CPU cores)
              memory: 512Gi 
              
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: booking
  spec:
    selector:
      matchLabels:
        app: booking
    template:
      metadata:
        labels:
          app: booking
      spec:
        imagePullSecrets:
        - name: acr-auth
        containers:
        - name: booking
          image: "studionestapi.azurecr.io/booking-service:latest"
          imagePullPolicy: Always
          ports:
          - containerPort: 8813
          env:
          - name: MONGODB
            valueFrom:
              secretKeyRef:
                name: booking-secret
                key: MONGODB_CONNECTION_STRING
          resources:
            requests:
              cpu: 50m  # 50 (0.05 CPU cores)
              memory: 256Mi  
            limits:
              cpu: 300m  #  (0.5 CPU cores)
              memory: 512Gi 
              
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: user
  spec:
    selector:
      matchLabels:
        app: user
    template:
      metadata:
        labels:
          app: user
      spec:
        imagePullSecrets:
        - name: acr-auth
        containers:
        - name: user
          image: "studionestapi.azurecr.io/user-service:latest"
          imagePullPolicy: Always
          ports:
          - containerPort: 8815
          env:
          - name: MONGODB
            valueFrom:
              secretKeyRef:
                name: user-secret
                key: MONGODB_CONNECTION_STRING
          resources:
            requests:
              cpu: 50m  # 50 (0.05 CPU cores)
              memory: 256Mi  
            limits:
              cpu: 300m  #  (0.5 CPU cores)
              memory: 512Gi 
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: contentlib
  spec:
    selector:
      matchLabels:
        app: contentlib
    template:
      metadata:
        labels:
          app: contentlib
      spec:
        imagePullSecrets:
        - name: acr-auth
        containers:
        - name: contentlib
          image: "studionestapi.azurecr.io/contentlib-service:latest"
          imagePullPolicy: Always
          ports:
          - containerPort: 8821
          env:
          - name: MONGODB
            valueFrom:
              secretKeyRef:
                name: contentlib-secret
                key: MONGODB_CONNECTION_STRING
          resources:
            requests:
              cpu: 50m  # 50 (0.05 CPU cores)
              memory: 256Mi  
            limits:
              cpu: 300m  #  (0.5 CPU cores)
              memory: 512Gi 
              
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: payment
  spec:
    selector:
      matchLabels:
        app: payment
    template:
      metadata:
        labels:
          app: payment
      spec:
        imagePullSecrets:
        - name: acr-auth
        containers:
        - name: payment
          image: "studionestapi.azurecr.io/payment-service:latest"
          imagePullPolicy: Always
          ports:
          - containerPort: 8817
          resources:
            requests:
              cpu: 50m  # 50 (0.05 CPU cores)
              memory: 256Mi  
            limits:
              cpu: 300m  #  (0.5 CPU cores)
              memory: 512Gi 
              
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: auth
  spec:
    selector:
      matchLabels:
        app: auth
    template:
      metadata:
        labels:
          app: auth
      spec:
        imagePullSecrets:
        - name: acr-auth
        containers:
        - name: auth
          image: "studionestapi.azurecr.io/auth-service:latest"
          imagePullPolicy: Always
          ports:
          - containerPort: 8491
          env:
          - name: MONGODB
            valueFrom:
              secretKeyRef:
                name: auth-secret
                key: MONGODB_CONNECTION_STRING
          - name: FIREBASE_WEB_API_KEY
            valueFrom:
              secretKeyRef:
                name: auth-secret
                key: FIREBASE_WEB_API_KEY
          resources:
            requests:
              cpu: 50m  # 50 (0.05 CPU cores)
              memory: 256Mi  
            limits:
              cpu: 300m  #  (0.5 CPU cores)
              memory: 512Gi 
              
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: aihelper
  spec:
    selector:
      matchLabels:
        app: aihelper
    template:
      metadata:
        labels:
          app: aihelper
      spec:
        imagePullSecrets:
        - name: acr-auth
        containers:
        - name: aihelper
          image: "studionestapi.azurecr.io/aihelper-service:latest"
          imagePullPolicy: Always
          ports:
          - containerPort: 8840
          env:
          - name: OPENAI_ORGANIZATION
            valueFrom:
              secretKeyRef:
                name: openai-secret
                key: ORGANIZATION
          - name: OPENAI_API_KEY
            valueFrom:
              secretKeyRef:
                name: openai-secret
                key: API_KEY
          resources:
            requests:
              cpu: 50m  # 50 (0.05 CPU cores)
              memory: 256Mi  
            limits:
              cpu: 300m  #  (0.5 CPU cores)
              memory: 512Gi 
              
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: client
  spec:
    selector:
      matchLabels:
        app: client
    template:
      metadata:
        labels:
          app: client
      spec:
        imagePullSecrets:
        - name: acr-auth
        containers:
        - name: client
          image: "studionestapi.azurecr.io/client-service:latest"
          imagePullPolicy: Always
          ports:
          - containerPort: 3000
          env:
          - name: HOST
            valueFrom:
              secretKeyRef:
                name: client-secret
                key: HOST
          resources:
            requests:
              cpu: 50m  # 50 (0.05 CPU cores)
              memory: 256Mi  
            limits:
              cpu: 300m  #  (0.5 CPU cores)
              memory: 512Gi 
