name: "Login to Azure CLI"
on:
  workflow_call:
  workflow_dispatch:
  # push: 
  #   branches:
  #     - main

concurrency:
  group: azcli-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  azure-login:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@main

      - name: Login via Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}