name: "Build and Push Images"
on:
  workflow_call:
  workflow_dispatch:
  # push: 
  #   branches:
  #     - main

concurrency:
  group: pytest-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build-and-push-images:
    strategy:
      matrix:
        service:
          # [service-name, docker-context, dockerfile-path]
          - [gateway, server, src/main/gateway/Dockerfile]
          - [user, server, src/main/user/Dockerfile]
          - [booking, server, src/main/booking/Dockerfile]
          - [contentlib, server, src/main/contentlib/Dockerfile]
          - [payment, api, src/main/payment/Dockerfile]
          - [roomman, api, src/main/roomman/Dockerfile]
          - [auth, api, src/main/auth/Dockerfile]
          - [aihelper, api, src/main/aihelper/Dockerfile]
          - [client, client, Dockerfile]
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@main

      - name: Login via Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Build and push images'
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}


      - name: Build and Push images
        env:
          REGISTRY_LOGIN_SERVER: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          SERVICE_NAME: ${{ matrix.service[0] }}
          CONTEXT: ${{ matrix.service[1] }}
          DOCKERFILE_PATH: ${{ matrix.service[2] }}
        run: ./scripts/buildandpushimages.sh
      # --- #