name: "Full Deploy"

on:
  workflow_dispatch:
  # push:
  #   branches:
  #   - main

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:

  sonarcloud:
    uses: ./.github/workflows/SonarQube.yml
    secrets: inherit

  build-and-push-images:
    uses: ./.github/workflows/container-registry.yml
    needs: sonarcloud
    secrets: inherit

  kubernetes-deploy:
    uses: ./.github/workflows/kubernetes-service.yml
    needs: build-and-push-images
    secrets: inherit
    permissions:
      actions: read
      contents: read
      id-token: write