name: "Deploy"
on:
  workflow_call:
  workflow_dispatch:
  # push: 
  #   branches:
  #     - main

concurrency:
  group: pytest-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  deployment:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: false
          

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push CONTAINER_NAME
        uses: ianbelcher/eks-kubectl-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: "eu-north-1"
          cluster_name: "studionest"
          kubernetes_version: v1.21.0
          args: apply -f "./deployment/deployment.yml"
      # --- #