name: "Build Images"
on:
  workflow_call:
  workflow_dispatch:
  push: 
    branches:
      - main

concurrency:
  group: pytest-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  deployment:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: false
          

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1


      - name: Build and push Docker images
        run: |
          echo "Building the images..."
          docker-compose build
          echo "Pushing the images..."
          docker-compose push
          echo "Images pushed to ECR"