name: "Kuberneted Deploy"
on:
  workflow_call:
  workflow_dispatch:

concurrency:
  group: kubernetes-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  kubernetes-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: false
      - name: Login via Azure CLI
        uses: azure/login@v1
        with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
  