name: "PyTests"
on:
  workflow_call:
  workflow_dispatch:
  # push: 
  #   branches:
  #     - main

concurrency:
  group: pytest-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  deployment:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: false

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: 'pip'

      - name: Install dependencies
        run: pip install -r server/src/test/requirements.txt

      - name: Run pytest
        run: ./pytest.sh